### ISSUE TITLE
克隆本机系统出现错误

### ISSUE THREAD

**Issue by Trumeet** [nkc3g4/wtg-assistant#1]
~可能是第一个 Issue？（划掉~

软件内选择 `克隆本机系统`，进度过后提示 `请 U 盘启动进行克隆`，我启动了。
CMD 自动运行了 `wpeinit` 和 `clone`，`clone` 运行中弹出了一个对话框，内容 `Error!`，然后就没然后了（（

关闭对话框后运行了 `DiskPart`，然后 `FastCopy`，我也不知道怎么操作，关闭闪过几个窗口就没了。之后我 `exit` 退出系统，重启 U 盘引导项丢失。

是不是哪里出了什么问题？求解。

**Comment by ghost** [comment]
请检查你的u盘容量

**Comment by gamecss** [comment]
请检查你的u盘容量

**Comment by ghost** [comment]
也可以看看你的系统是不是ghost阉割版

**Comment by ghost** [comment]
看看你的u盘是不是即插即用（upnp）

**Comment by Trumeet** [comment]
> 请检查你的u盘容量

够用

> 也可以看看你的系统是不是ghost阉割版

不是


> 看看你的u盘是不是即插即用（upnp）

是

**Comment by Trumeet** [comment]
算了，很就不用这工具了，暂且告一段落吧。
